name: Validate code in the merge queue

on:
  merge_group:
  pull_request:

jobs:
  validate-merge-group:
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Display info
      run: | 
        pwd
        tree -a -I '.git'
        git status
    - name: Run slow CI (emulated by a long sleep)
      run: sleep 300
    - name: pr test
      run: ./merge_group_test.bash
